[package]
name = "observability"
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
