[package]
name = "indexer"
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
api.workspace = true
decoder.workspace = true
dotenvy.workspace = true
ingestion.workspace = true
rpc.workspace = true
sqlx.workspace = true
storage.workspace = true
tokio.workspace = true
