[package]
name = "api"
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
async-graphql.workspace = true
async-graphql-axum = "7"
axum.workspace = true
metrics-exporter-prometheus.workspace = true
serde.workspace = true
sqlx.workspace = true
storage.workspace = true
tokio.workspace = true
tracing.workspace = true
