[package]
name = "ingestion"
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bigdecimal.workspace = true
decoder.workspace = true
futures.workspace = true
rpc.workspace = true
storage.workspace = true
tokio.workspace = true
